# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in voll.gemspec
gemspec

gem 'rake', '~> 13.0'

# Testing gems
gem 'debug'
gem 'minitest', '~> 5.16'
gem 'rubocop', '~> 1.21'
gem 'simplecov'

# dev gems
gem 'ruby-lsp', require: false
gem 'solargraph', require: false
gem 'yard', require: false
